export const skills = [
  "JavaScript",
  "TypeScript",
  "Jest",
  "Jasmine",
  "Webpack",
  "Grunt",
  "Gulp",
  "Babel",
  "Craco",
  "React",
  "Tailwind",
  "Redux",
  "XState",
  "Node",
  "PHP",
  "Python",
  "AWS Lambda",
  "AWS Cloudwatch",
  "Serverless",
  "GitHub Actions",
  "Jenkins",
  "JIRA",
  "Confluence",
  "Netlify",
  "Material UI",
  "Git",
  "Postman",
  "MySQL",
  "Presenting",
  "Karaoke",
];

export const skillsAndDescriptions = [
  {skill: "JavaScript", description: "super proficient"},
  {skill: "TypeScript", description: "super proficient"},
  {skill: "Jest", description: "we love testing our code"},
  {skill:"Jasmine", description: "we still love testing our code"},
  {skill:"Webpack", description: "compiler works"},
  {skill:"Grunt", description: "compiler works"},
  {skill:"Gulp", description: "compiler works"},
  {skill:"Babel", description: "compiler works"},
  {skill:"Craco", description: "react compiling"},
  {skill:"React", description: "react is everything"},
  {skill:"Tailwind", description: "newly fascinated with tailwind, description: loving it"},
  {skill:"Redux", description: "state management is a big win"},
  {skill:"XState", description: "state management still winning"},
  {skill:"Node", description: "node is by far my favorite "},
  {skill:"PHP", description: "the elephant is king "},
  {skill:"Python", description: "fun for playing with machine learning"},
  {skill:"AWS Lambda", description: "serverless is the future!"},
  {skill:"AWS Cloudwatch", description: "logging and metrics all day "},
  {skill:"Serverless", description: "serverless framework, description: very confusing name"},
  {skill:"GitHub Actions", description: "easily my favorite way to deploy code"},
  {skill:"Jenkins", description: "no longer my favorite way to deploy code"},
  {skill:"JIRA", description: "trello, description: but you need a degree to use it"},
  {skill:"Confluence", description: "the endless wiki of the world"},
  {skill:"Netlify", description: "let's get things on the internet"},
  {skill:"Material UI", description: "makes life so easy if you don't need a lot"},
  {skill:"Git", description: "i mean. it's a must"},
  {skill:"Postman", description: "testing endpoints"},
  {skill:"MySQL", description: "don't drop tables"},
  {skill:"Presenting", description: "love public speaking, description: give me a stage"},
  {skill:"Karaoke", description: "it's my one party trick"},
]
  
 
